version: '3'
services:
  postgres-server:
    image: 'postgres:13.1-alpine'
    container_name: postgres-server
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  jurema-state-api:
    container_name: jurema-state-api
    build:
      context: jurema-state-api
    image: jurema-state-api:latest
    depends_on:
      - postgres-server
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-server:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  jurema-state-population-api:
    container_name: jurema-state-population-api
    build:
      context: jurema-state-population-api
    image: jurema-state-population-api:latest
    depends_on:
      - postgres-server
    restart: always
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-server:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
